### PR TITLE
Add in HTML pre tag to preserve line breaks and whitespace. 

### PR DESCRIPTION
**Pull request by alyssadelaine**
NOTE: This will put text in a monospace font like Courier

Closes https://github.com/developmentseed/api.work.vote/issues/61

### CODE REVIEW

**Comment by alyssadelaine** [comment]
@scisco Has this been pushed to the website?

**Comment by scisco** [comment]
Nope. working on it right now.

**Comment by alyssadelaine** [comment]
Thanks!

**Comment by scisco** [comment]
This was deployed last week and it's ready to be merged.

**Pull request merged**
